backend and post page update
4GeeksAcademy/jnorestin-the-help pull request #8
Opened 2023-06-16 23:20 UTC by Donducci

2023-06-16 23:49 UTC, RonaldineP requested changes

2023-06-16 23:49 UTC, RonaldineP commented on src/front/js/component/navbar.js
> -            <span className="navbar-brand mb-0 h1">Help</span>
add this part

2023-06-16 23:55 UTC, RonaldineP approved these changes

2023-06-17 00:08 UTC, jnorestin approved these changes

2023-06-17 00:08 UTC, merged

2023-06-17 09:18 UTC, Donducci commented
Dear RonaldineP,

Thank you for requesting changes on my pull request. I appreciate your
feedback and will work on incorporating your suggestions.

Best regards,

[Donduchi]

On Fri, Jun 16, 2023 at 7:08 PM Jonathan Norestin ***@***.***>
wrote:

> Merged #8 <https://github.com/4GeeksAcademy/jnorestin-the-help/pull/8>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/4GeeksAcademy/jnorestin-the-help/pull/8#event-9557020031>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5A2TV2HGADLFOWIEXG4VBTXLTYQ7ANCNFSM6AAAAAAZJ2N7BY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>